CXX = g++

ROOT_DIR = ./
BOOST_DIR=/data/boost-install/

INTERFACE_DIR = $(ROOT_DIR)/interface

SOURCES = BaseBusiness.cpp \
		  ConnectionManager.cpp \
		  GlobalConfig.cpp \
		  TopupService.cpp \
		  HttpClient.cpp \
		  TopupUtils.cpp 

OBJS = $(SOURCES:.cpp=.o)
THRIFT_OBJS = $(INTERFACE_DIR)/Topup.o \
			  $(INTERFACE_DIR)/TopupInterface_types.o  \
			  $(INTERFACE_DIR)/TopupInterface_constants.o

UTILS_OBJS = HttpClient.o

TOPUP_OBJS = TopupImpl.o \
			 HttpClient.o \
			 TopupUtils.o \
			 $(INTERFACE_DIR)/TopupInterface_types.o \
			 ChannelSLS.o

TOPUP_SO = topup.so


CXXFLAG = -g -Wall 
SHARE_FLAG = -fPIC

INCS = -I../include \
	   -I../include/occi \
	   -I../include/thrift \
	   -I$(BOOST_DIR)/include \
	   -I./interface \
	   -I../include/fastcgi \
	   -I../lib64/common/include

LIBS = -L../lib \
	   -L../lib64/common/lib

TEST = test_httpclient

all: oracle_client topup_server topup.fcg $(TEST) $(TOPUP_SO)


.cpp.o:
	$(CXX) -c $(CXXFLAG) $(INCS) $(LIBS) $(SHARE_FLAG)  $< -o $@ 


oracle_client: oracle.o
	$(CXX) $(CPPFLAG) $(INCS) $(LIBS)  -locci  -lclntsh -lnnz11 -lglog -lpthread -o $@  $<

$(TOPUP_SO): $(TOPUP_OBJS)
	$(CXX) -g -fPIC -shared -o $@ $^

topup_server: $(OBJS) TopupServer.o
	$(CXX) $(CPPFLAG) $(INCS) $(LIBS)  TopupServer.o $(OBJS) $(THRIFT_OBJS) -Wl,--rpath -Wl,/data/occi/lib -locci -lclntsh -lnnz11 -lglog -liniparser -lcurl -lthrift -lthriftnb -lpthread -levent -lcommon -o $@

topup.fcg: $(UTILS_OBJS) TopupFcgi.o
	$(CXX) $(CPPFLAG) $(INCS) $(LIBS)  TopupFcgi.o $(UTILS_OBJS) $(THRIFT_OBJS) -lfcgi -Wl,--rpath -Wl,/data/occi/lib -lcurl -lthrift -lthriftnb -lpthread -levent -o $@


test_httpclient: HttpClient.o Test_HttpClient.o
	$(CXX) $(CPPFLAG) $(INCS) $(LIBS)  Test_HttpClient.o HttpClient.o -lcurl -o $@

clean:
	rm *.o -f
