// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Topup.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::topupinterface;

class TopupHandler : virtual public TopupIf {
 public:
  TopupHandler() {
    // Your initialization goes here
  }

  void SendRequest(std::string& _return, const TopupRequest& request) {
    // Your implementation goes here
    printf("SendRequest\n");
  }

  int32_t Admin(const ManageRequest& request) {
    // Your implementation goes here
    printf("Admin\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<TopupHandler> handler(new TopupHandler());
  shared_ptr<TProcessor> processor(new TopupProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

