/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TopupInterface_CONSTANTS_H
#define TopupInterface_CONSTANTS_H

#include "TopupInterface_types.h"

namespace topupinterface {

class TopupInterfaceConstants {
 public:
  TopupInterfaceConstants();

};

extern const TopupInterfaceConstants g_TopupInterface_constants;

} // namespace

#endif
